// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHgUV0fq54V_C-r9wqNOB8W6HBEQOeYg',
    appId: '1:768614225717:android:1a4e2d18f4cb034a7a1e7c',
    messagingSenderId: '768614225717',
    projectId: 'donviva',
    storageBucket: 'donviva.firebasestorage.app',
  );

  // Windows uses the same Firebase project — reuses Android credentials for dev.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaHgUV0fq54V_C-r9wqNOB8W6HBEQOeYg',
    appId: '1:768614225717:android:1a4e2d18f4cb034a7a1e7c',
    messagingSenderId: '768614225717',
    projectId: 'donviva',
    storageBucket: 'donviva.firebasestorage.app',
  );
}
